# Generated by Django 3.2.11 on 2023-07-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
